### ISSUE TITLE
FYI: Implementation in Binaryen

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/extended-name-section#1]
This proposal has been partially implemented in Binaryen (PR: https://github.com/WebAssembly/binaryen/pull/3162), in particular the subsections for

* Memory names (Binaryen currently supports exactly one)
* Table names (Binaryen currently supports exactly one) and
* Global names

Binaryen does not yet emit respectively recognize subsections for

* Label names
* Type names
* Table element names
* Data segment names

but it should of course be possible to support these as well, perhaps with the exception of label names, which don't seem very useful to preserve in context of an optimizer that often removes existing or adds new labeled instructions, even though it might be possible at the expense of added complexity.

**Comment by ashleynh** [comment]
Closing as completed as all but label names are emitted and recognized in Binaryen. Will open a new issue to track this work.
